---
baseURL: http://blog.kars7e.io/
disablePathToLower: true
languageCode: en-us
title: kars7e's Blog
googleAnalytics: UA-7878188-6
disqusShortname: kars7e
theme: slim_custom
pygmentsstyle: colorful
taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"
permalinks:
  post: /:year/:month/:day/:title/

