---
baseURL: http://blog.kars7e.io/
disablePathToLower: true
languageCode: en-us
title: kars7e's Blog
googleAnalytics: UA-7878188-6
disqusShortname: kars7e
theme: slim_custom
pygmentsstyle: colorful
taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"
permalinks:
  post: /:year/:month/:day/:title/
enableRobotsTXT: true
params:
  Subtitle: "Personal blog of Karol Stepniewski"
  GithubID: "kars7e"
  TwitterID: "kars7e"
  LinkedInID: "karolstepniewski"
  AnalyticsID: "UA-7878188-6"
  DisqusShortname: "kars7e"
  Summary: true # takes true or false
  Content: false # takes true or false
  FooterMsg: "2017 Karol Stepniewski"

